<? include "../template.php" ?>
<html>
<head>
<title>POVRAY renderings</title>
</head>
<body>
<p>PovRay is a ray tracing and rendering engine. Using simple contructional code, one can build advanced objects that look incredibly accurate. </p>
<ul>
  <li>2007-07-06: <a href="reflection/">Reflection</a></li>
</ul>  

<p>Some examples of the output of this program:</p>
<table><tr><td><a href="bg-medium.png"><img src="bg-small.png" alt="torus" /></a></td><td><a href="beams2-med.png"><img src="beams2-small.png" alt="beams" /></a></td></tr><tr><td><a href="bg.pov">Background</a></td><td><a href="beams2.pov">Beams</a></td></tr></table>
<p>Also, you can do even niftier things, like adding clouds, or generating mountainous height fields:<br />
<a href="heightfield-big.png"><img src="heightfield.png" alt="heightfield" /></a></p>
<p>Everyone needs shapes. Generated by a short code <a href="shapes.pov">code</a> snippet, we get:<br />
<img src="shapes.png" alt="shapes" /></p>
<p>This is just a small sampling of povray's power. For more examples, see the <a href="http://www.irtc.org">Internet Ray Tracing Compentation</a>, with absolutely incredible examples.</p>
</body>
</html>
